language: node_js
node_js:
  - "6"

deploy:
  api_key:
    secure: WmPXgAqOqEU2EEX0U02AV3kiLvv5eoi0CMY3lXI68ucafVUAkOrec9/NqwWSe55k3748Qx1fh94TtQmFKXrKc/TteHVFoNDuSQj7RnbDlBBLBS6kGgwaw8y4ueIcDmAcIxUiT2ze2ZBO/Q2bj1sp2ORYu8bXhYbqDyV3qYqVDzH7SFG4Z7XHfyVvrypu7sFgNfizlp0qlyvVsP5d1dHf8UhRs/csxIFGvdtaY279f8/XEkJdoueluakP8V1xka3O8E5vR8TnFLkVd5GdB74sFZJf8OYc12+2EWMj1o3evdIG3MTe4te4LKZijXNrK4KXJR09bM+/374PWtSPIYtvwOc0e0MQ9gTF+KXb0Vy5Uk0Fnl5XLu0240MhEloTYSeTKpge1nQLZqPCpFkC5uWFHtQVyler4PqYn41sjZLecOLtQNfZjfo1QGIWBUlSPz779bPuUj5wsFUx43dvs1zjK50eqeY3jHakLxG4+zSRbQ7xv6+z3mNpSuggzS48+u+AmDRanscudLhKpdFhlBpjmoItA3eBogaHdckrkwVjh/G+iWfnGNBeEAwa027sf3sME5PH4g6vaJe42lcZvBqddRwcLwNztgP0R9sstBXnr+sDNgD+x4KZH8DRcZkpUbY0hu5NIMMdCO6MNv/WaMFRk04AUjXqK/ILWXgGz2Pg7S0=
